In [1]:
import pandas as pd
score = {'kor':90, 'eng':80, 'math':100}
print(pd.Series(score))

kor      90
eng      80
math    100
dtype: int64

In [2]:
score = pd.Series([100,90,95,50])
print(score)

0    100
1     90
2     95
3     50
dtype: int64

In [3]:
import numpy as np
arr = np.arange(1,9,0.5)
d = pd.Series(arr)
print(d)

0     1.0
1     1.5
2     2.0
3     2.5
4     3.0
5     3.5
6     4.0
7     4.5
8     5.0
9     5.5
10    6.0
11    6.5
12    7.0
13    7.5
14    8.0
15    8.5
dtype: float64

In [4]:
score = pd.Series([90,80,10], index=['국어','수학','영어'])
print(score)

국어    90
수학    80
영어    10
dtype: int64

In [5]:
score = [10,30,40]
index_score = ['국어','수학','영어']
print(pd.Series(score, index=index_score))

국어    10
수학    30
영어    40
dtype: int64

In [6]:
price = [1500,600,300]
what = ['볼펜','딱풀','지우개']
print(pd.Series(price, index=what))

볼펜     1500
딱풀      600
지우개     300
dtype: int64

In [7]:
dic_data = {'볼펜': 1500, '딱풀':600,'지우개':400}
idx = ['볼펜','딱풀','지우개','공책']
price = pd.Series(dic_data, index=idx)
print(price)

볼펜     1500.0
딱풀      600.0
지우개     400.0
공책        NaN
dtype: float64

In [8]:
pd.isnull(price)

볼펜     False
딱풀     False
지우개    False
공책      True
dtype: bool

In [9]:
pd.notnull(price)

볼펜      True
딱풀      True
지우개     True
공책     False
dtype: bool

In [10]:
del price['공책']
print(price)

볼펜     1500.0
딱풀      600.0
지우개     400.0
dtype: float64

In [11]:
[price >=500]

[볼펜      True
 딱풀      True
 지우개    False
 dtype: bool]

In [12]:
print(price[price >=500])

볼펜    1500.0
딱풀     600.0
dtype: float64

In [13]:
price['공책']= 1200

In [14]:
price

볼펜     1500.0
딱풀      600.0
지우개     400.0
공책     1200.0
dtype: float64

In [15]:
price['지우개'] = 900
price['딱풀']=1200

In [16]:
del price['지우게']
print(price)

KeyError: '지우게'

In [17]:
#실습 1
import numpy as np
import pandas as pd
dic_data = {'홍길동':20, '김유신':22, '강감찬':21, '라이온':19, '유관순':24}
profile = pd.Series(dic_data)
print(profile)

홍길동    20
김유신    22
강감찬    21
라이온    19
유관순    24
dtype: int64

In [18]:
df = pd.DataFrame([[90,80,70],[100,90,95],[80,80,80],[90,95,90],[85,85,80]], 
                  index=[20231231,20231232,20231233, 20231234,20231235], 
                  columns = ['kor','eng','math'])
print(df)

          kor  eng  math
20231231   90   80    70
20231232  100   90    95
20231233   80   80    80
20231234   90   95    90
20231235   85   85    80

In [19]:
df['sci'] = [90,100,85,90,80]
print(df)

          kor  eng  math  sci
20231231   90   80    70   90
20231232  100   90    95  100
20231233   80   80    80   85
20231234   90   95    90   90
20231235   85   85    80   80

In [20]:
df['sum'] = 0
print(df)

          kor  eng  math  sci  sum
20231231   90   80    70   90    0
20231232  100   90    95  100    0
20231233   80   80    80   85    0
20231234   90   95    90   90    0
20231235   85   85    80   80    0

In [21]:
df.loc[20231236] = [90,90,85,90,0]
print(df)

          kor  eng  math  sci  sum
20231231   90   80    70   90    0
20231232  100   90    95  100    0
20231233   80   80    80   85    0
20231234   90   95    90   90    0
20231235   85   85    80   80    0
20231236   90   90    85   90    0

In [22]:
df.loc[20231237] = 0
print(df)

          kor  eng  math  sci  sum
20231231   90   80    70   90    0
20231232  100   90    95  100    0
20231233   80   80    80   85    0
20231234   90   95    90   90    0
20231235   85   85    80   80    0
20231236   90   90    85   90    0
20231237    0    0     0    0    0

In [23]:
df.drop('sum',axis=1, inplace=True)
print(df)

          kor  eng  math  sci
20231231   90   80    70   90
20231232  100   90    95  100
20231233   80   80    80   85
20231234   90   95    90   90
20231235   85   85    80   80
20231236   90   90    85   90
20231237    0    0     0    0

In [24]:
df.drop(20231237, axis=0, inplace=True)
print(df)

          kor  eng  math  sci
20231231   90   80    70   90
20231232  100   90    95  100
20231233   80   80    80   85
20231234   90   95    90   90
20231235   85   85    80   80
20231236   90   90    85   90

In [25]:
df.insert(0, 'name',['홍길동','김유신','강감찬','유관순','정약용','이순신'])
print(df)

         name  kor  eng  math  sci
20231231  홍길동   90   80    70   90
20231232  김유신  100   90    95  100
20231233  강감찬   80   80    80   85
20231234  유관순   90   95    90   90
20231235  정약용   85   85    80   80
20231236  이순신   90   90    85   90

In [26]:
df.loc[20231230] = ['이정재',97,95,90,88]
df = df.sort_index(ascending=True)
print(df)

         name  kor  eng  math  sci
20231230  이정재   97   95    90   88
20231231  홍길동   90   80    70   90
20231232  김유신  100   90    95  100
20231233  강감찬   80   80    80   85
20231234  유관순   90   95    90   90
20231235  정약용   85   85    80   80
20231236  이순신   90   90    85   90

In [27]:
df.rename(columns = {'name':'이름','kor':'국어','eng':'영어','math':'수학','sci':'과학'}, inplace=True)
print(df)

           이름   국어  영어  수학   과학
20231230  이정재   97  95  90   88
20231231  홍길동   90  80  70   90
20231232  김유신  100  90  95  100
20231233  강감찬   80  80  80   85
20231234  유관순   90  95  90   90
20231235  정약용   85  85  80   80
20231236  이순신   90  90  85   90

In [28]:
df.rename(index={20231230:20231237},inplace=True)
df = df.sort_index(ascending=True)
print(df)

           이름   국어  영어  수학   과학
20231231  홍길동   90  80  70   90
20231232  김유신  100  90  95  100
20231233  강감찬   80  80  80   85
20231234  유관순   90  95  90   90
20231235  정약용   85  85  80   80
20231236  이순신   90  90  85   90
20231237  이정재   97  95  90   88

In [29]:
df['이름']

20231231    홍길동
20231232    김유신
20231233    강감찬
20231234    유관순
20231235    정약용
20231236    이순신
20231237    이정재
Name: 이름, dtype: str

In [30]:
df[['이름','국어','수학']]

           이름   국어  수학
20231231  홍길동   90  70
20231232  김유신  100  95
20231233  강감찬   80  80
20231234  유관순   90  90
20231235  정약용   85  80
20231236  이순신   90  85
20231237  이정재   97  90

In [31]:
df['총점']= df['국어']+df['수학'] + df['영어'] + df['과학']
print(df)

           이름   국어  영어  수학   과학   총점
20231231  홍길동   90  80  70   90  330
20231232  김유신  100  90  95  100  385
20231233  강감찬   80  80  80   85  325
20231234  유관순   90  95  90   90  365
20231235  정약용   85  85  80   80  330
20231236  이순신   90  90  85   90  355
20231237  이정재   97  95  90   88  370

In [32]:
df['평균'] = df['총점'] /4
print(df)

           이름   국어  영어  수학   과학   총점     평균
20231231  홍길동   90  80  70   90  330  82.50
20231232  김유신  100  90  95  100  385  96.25
20231233  강감찬   80  80  80   85  325  81.25
20231234  유관순   90  95  90   90  365  91.25
20231235  정약용   85  85  80   80  330  82.50
20231236  이순신   90  90  85   90  355  88.75
20231237  이정재   97  95  90   88  370  92.50

In [33]:
del df['총점']
print(df)

           이름   국어  영어  수학   과학     평균
20231231  홍길동   90  80  70   90  82.50
20231232  김유신  100  90  95  100  96.25
20231233  강감찬   80  80  80   85  81.25
20231234  유관순   90  95  90   90  91.25
20231235  정약용   85  85  80   80  82.50
20231236  이순신   90  90  85   90  88.75
20231237  이정재   97  95  90   88  92.50

In [34]:
df['평균'] >=90

20231231    False
20231232     True
20231233    False
20231234     True
20231235    False
20231236    False
20231237     True
Name: 평균, dtype: bool

In [35]:
df[df['평균']>=90]

           이름   국어  영어  수학   과학     평균
20231232  김유신  100  90  95  100  96.25
20231234  유관순   90  95  90   90  91.25
20231237  이정재   97  95  90   88  92.50

In [36]:
import pandas as pd
df = pd.read_csv("./data/job.csv")
print(df)

  name from  age  job
0  나은미  경기    23   학생
1  정다혜   서울   35   교사
2  이은형   충남   29  공무원
3  김은미   강원   31  회사원
4  최성주   제주   35  매니저
5  오달수   강원   55   배우

In [37]:
type(df)

pandas.DataFrame

In [38]:
df.dtypes

name      str
from      str
age     int64
job       str
dtype: object

In [39]:
df.shape

(6, 4)

In [40]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [41]:
df.columns

Index(['name', 'from', 'age', 'job'], dtype='str')

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      str
 1   from    6 non-null      str
 2   age     6 non-null      int64
 3   job     6 non-null      str
dtypes: int64(1), str(3)
memory usage: 324.0 bytes

In [43]:
df.describe()

             age
count   6.000000
mean   34.666667
std    10.911767
min    23.000000
25%    29.500000
50%    33.000000
75%    35.000000
max    55.000000

In [44]:
df.values

array([['나은미', '경기 ', 23, '학생'],
       ['정다혜', '서울', 35, '교사'],
       ['이은형', '충남', 29, '공무원'],
       ['김은미', '강원', 31, '회사원'],
       ['최성주', '제주', 35, '매니저'],
       ['오달수', '강원', 55, '배우']], dtype=object)

In [45]:
df1 = pd.read_csv("./data/job1.csv")
df = pd.concat([df,df1])
print(df)

  name from  age  job
0  나은미  경기    23   학생
1  정다혜   서울   35   교사
2  이은형   충남   29  공무원
3  김은미   강원   31  회사원
4  최성주   제주   35  매니저
5  오달수   강원   55   배우
0   김민  전남    23   학생
1  정다은   경기   30  회사원
2  김인형   대전   38  공무원
3  최민수   충북   40   백수
4  최성미   제주   20  미용사
5  오미지   강원   13   학생

In [46]:
df.reset_index(drop=True, inplace=True)
print(df)

   name from  age  job
0   나은미  경기    23   학생
1   정다혜   서울   35   교사
2   이은형   충남   29  공무원
3   김은미   강원   31  회사원
4   최성주   제주   35  매니저
5   오달수   강원   55   배우
6    김민  전남    23   학생
7   정다은   경기   30  회사원
8   김인형   대전   38  공무원
9   최민수   충북   40   백수
10  최성미   제주   20  미용사
11  오미지   강원   13   학생

In [47]:
df['판매금액'] =0
print(df)

   name from  age  job  판매금액
0   나은미  경기    23   학생     0
1   정다혜   서울   35   교사     0
2   이은형   충남   29  공무원     0
3   김은미   강원   31  회사원     0
4   최성주   제주   35  매니저     0
5   오달수   강원   55   배우     0
6    김민  전남    23   학생     0
7   정다은   경기   30  회사원     0
8   김인형   대전   38  공무원     0
9   최민수   충북   40   백수     0
10  최성미   제주   20  미용사     0
11  오미지   강원   13   학생     0

In [48]:
df['판매금액'] = df['age'] *4
print(df)

   name from  age  job  판매금액
0   나은미  경기    23   학생    92
1   정다혜   서울   35   교사   140
2   이은형   충남   29  공무원   116
3   김은미   강원   31  회사원   124
4   최성주   제주   35  매니저   140
5   오달수   강원   55   배우   220
6    김민  전남    23   학생    92
7   정다은   경기   30  회사원   120
8   김인형   대전   38  공무원   152
9   최민수   충북   40   백수   160
10  최성미   제주   20  미용사    80
11  오미지   강원   13   학생    52

In [49]:
df.head(5)

  name from  age  job  판매금액
0  나은미  경기    23   학생    92
1  정다혜   서울   35   교사   140
2  이은형   충남   29  공무원   116
3  김은미   강원   31  회사원   124
4  최성주   제주   35  매니저   140

In [50]:
df.tail(5)

   name from  age  job  판매금액
7   정다은   경기   30  회사원   120
8   김인형   대전   38  공무원   152
9   최민수   충북   40   백수   160
10  최성미   제주   20  미용사    80
11  오미지   강원   13   학생    52

In [51]:
import numpy as np
arr = df.to_numpy()
print("이름    출신    나이    직업   판매금액")
for i,k,j,l,m in arr :
    print(i,k,j,l,m, sep="\t")

이름    출신    나이    직업   판매금액
나은미	경기 	23	학생	92
정다혜	서울	35	교사	140
이은형	충남	29	공무원	116
김은미	강원	31	회사원	124
최성주	제주	35	매니저	140
오달수	강원	55	배우	220
김민	전남 	23	학생	92
정다은	경기	30	회사원	120
김인형	대전	38	공무원	152
최민수	충북	40	백수	160
최성미	제주	20	미용사	80
오미지	강원	13	학생	52

In [52]:
group_data = df.groupby(['from']).sum()
print(group_data)

           name  age      job  판매금액
from
강원    김은미오달수오미지   99  회사원배우학생   396
경기          정다은   30      회사원   120
경기          나은미   23       학생    92
대전          김인형   38      공무원   152
서울          정다혜   35       교사   140
전남           김민   23       학생    92
제주       최성주최성미   55   매니저미용사   220
충남          이은형   29      공무원   116
충북          최민수   40       백수   160

In [53]:
df.groupby(['from'], as_index = False).sum()

  from       name  age      job  판매금액
0   강원  김은미오달수오미지   99  회사원배우학생   396
1   경기        정다은   30      회사원   120
2  경기         나은미   23       학생    92
3   대전        김인형   38      공무원   152
4   서울        정다혜   35       교사   140
5  전남          김민   23       학생    92
6   제주     최성주최성미   55   매니저미용사   220
7   충남        이은형   29      공무원   116
8   충북        최민수   40       백수   160

In [54]:
df.to_csv("./data/job통합.csv")

In [55]:
import pandas as pd
df1 = pd.read_csv("./data/branch_inventory.csv")
df1

   지점코드  세탁기  에어컨  냉장고
0  K303    8   23   11
1  K303   41   13   22
2  N101    2   12   11
3  N101    7    8   23
4  W203    8   28    7
5  W203    5   15   12
6  S301    3   31   13
7  S301    6   15   14
8  E425    8   42   32
9  E425    1   23   11

In [56]:
df2 = pd.read_csv("./data/brance_code.csv")
df2

   지점코드  지점명
0  K303  강서점
1  N101  남부점
2  W203  서부점
3  S301  서울점
4  E425  동서점

In [57]:
df = pd.merge(df1, df2, how="inner", on="지점코드")
df

   지점코드  세탁기  에어컨  냉장고  지점명
0  K303    8   23   11  강서점
1  K303   41   13   22  강서점
2  N101    2   12   11  남부점
3  N101    7    8   23  남부점
4  W203    8   28    7  서부점
5  W203    5   15   12  서부점
6  S301    3   31   13  서울점
7  S301    6   15   14  서울점
8  E425    8   42   32  동서점
9  E425    1   23   11  동서점

In [58]:
df.groupby(df['지점코드']).sum()

      세탁기  에어컨  냉장고     지점명
지점코드
E425    9   65   43  동서점동서점
K303   49   36   33  강서점강서점
N101    9   20   34  남부점남부점
S301    9   46   27  서울점서울점
W203   13   43   19  서부점서부점