In [1]:
import pandas as pd
score = {'kor':90,'eng':80,'math':100,'sci':98}
score = pd.Series(score)
score

kor      90
eng      80
math    100
sci      98
dtype: int64

In [2]:
grade = [100,90,80,70]
grade = pd.Series(grade)
grade

0    100
1     90
2     80
3     70
dtype: int64

In [3]:
import numpy as np
arr = np.arange(1,10,2)
arr = pd.Series(arr)
arr

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [4]:
age = pd.Series([10,30,42],index=['나','엄마','아빠'])
age

나     10
엄마    30
아빠    42
dtype: int64

In [5]:
age = [10,14,15]
idx = ['나','이모','오빠']
ages = pd.Series(age, index= idx)
ages

나     10
이모    14
오빠    15
dtype: int64

In [6]:
g ={'kor':90, 'math':100, 'sci':80}
idx = ['kor','math','sci', 'eng']
guk = pd.Series(g, index= idx)
guk

kor      90.0
math    100.0
sci      80.0
eng       NaN
dtype: float64

In [7]:
pd.isnull(guk)

kor     False
math    False
sci     False
eng      True
dtype: bool

In [8]:
pd.isnull(guk).sum()

np.int64(1)

In [9]:
pd.notnull(guk)

kor      True
math     True
sci      True
eng     False
dtype: bool

In [10]:
del guk['eng']

In [11]:
guk

kor      90.0
math    100.0
sci      80.0
dtype: float64

In [12]:
[guk >=90]

[kor      True
 math     True
 sci     False
 dtype: bool]

In [13]:
[guk[guk >=90]]

[kor      90.0
 math    100.0
 dtype: float64]

In [14]:
guk['eng']= 89

In [15]:
gugk

NameError: name 'gugk' is not defined

In [16]:
guk

kor      90.0
math    100.0
sci      80.0
eng      89.0
dtype: float64

In [17]:
info = {'학번' : [20240001, 2022100392, 2022100393], '나이' : [23,22,21], '이름 ': ['가은','민서','수진'], '성적' : [100,20,90]}
df = pd.DataFrame(info)

In [18]:
df

           학번  나이 이름    성적
0    20240001  23  가은  100
1  2022100392  22  민서   20
2  2022100393  21  수진   90

In [19]:
df2 = pd.DataFrame([[100,100,90],[90,80,70],[60,70,50]], index = [20240001, 2022100392, 2022100393], columns = ['국어','수학','영어'])
df2

             국어   수학  영어
20240001    100  100  90
2022100392   90   80  70
2022100393   60   70  50

In [20]:
df2['과학'] = [100,80,90]
df2.loc[2022100394] = [100,90,66,90]
df2

             국어   수학  영어   과학
20240001    100  100  90  100
2022100392   90   80  70   80
2022100393   60   70  50   90
2022100394  100   90  66   90

In [21]:
df2.drop('과학', axis=1, inplace=True)
df2.drop(2022100394, axis=0,inplace=True)
df2

             국어   수학  영어
20240001    100  100  90
2022100392   90   80  70
2022100393   60   70  50

In [22]:
df2.insert(0, '한국사',[100,97,89], allow_duplicates=False)
df2

            한국사   국어   수학  영어
20240001    100  100  100  90
2022100392   97   90   80  70
2022100393   89   60   70  50

In [23]:
df2.loc[2022100390] = [100,98,90,100]

In [24]:
df2.sort_index(ascending = True)

            한국사   국어   수학   영어
20240001    100  100  100   90
2022100390  100   98   90  100
2022100392   97   90   80   70
2022100393   89   60   70   50

In [25]:
df2.rename(columns = {'한국사':'history', '국어':'korean','수학':'math', '영어':'english'}, inplace=True)
df2

            history  korean  math  english
20240001        100     100   100       90
2022100392       97      90    80       70
2022100393       89      60    70       50
2022100390      100      98    90      100

In [26]:
df2.rename(index = {20240001:22100391, 2022100392:22100392, 2022100393:22100393}, inplace=True)
df2

            history  korean  math  english
22100391        100     100   100       90
22100392         97      90    80       70
22100393         89      60    70       50
2022100390      100      98    90      100

In [27]:
import pandas as pd
stationery = {"볼펜" : 1500, "딱풀" : 600, "지우개" : 300}
stationery = pd.Series(stationery)

In [28]:
stationery

볼펜     1500
딱풀      600
지우개     300
dtype: int64

In [29]:
stationery = ['볼펜', '딱풀', '지우개']
price = [1500,600,300]
thing = pd.Series(price, index= stationery)
thing

볼펜     1500
딱풀      600
지우개     300
dtype: int64

In [30]:
things = pd.Series([1500,600,300], index = ['볼펜','지우개','딱풀'])
things

볼펜     1500
지우개     600
딱풀      300
dtype: int64

In [31]:
del things['볼펜']

In [32]:
things

지우개    600
딱풀     300
dtype: int64

In [33]:
things['볼펜'] = 1500

In [34]:
things

지우개     600
딱풀      300
볼펜     1500
dtype: int64

In [35]:
things.sort_values(ascending = False)

볼펜     1500
지우개     600
딱풀      300
dtype: int64

In [36]:
df2

            history  korean  math  english
22100391        100     100   100       90
22100392         97      90    80       70
22100393         89      60    70       50
2022100390      100      98    90      100

In [37]:
import pandas as pd
import numpy as np
info = {'학번' : [20240001, 2022100392, 2022100393], '나이' : [22,20,23], '성적' : [100,90,80]}
df = pd.DataFrame(info)
df

           학번  나이   성적
0    20240001  22  100
1  2022100392  20   90
2  2022100393  23   80

In [38]:
df2 = pd.DataFrame([[100,90], [89,90]], index = [20240001, 2022100392], columns=['국어','수학'])
df2

             국어  수학
20240001    100  90
2022100392   89  90

In [39]:
df2['과학'] = [100,80]
df2.loc[2022100390]= [70,80,92]
df2

             국어  수학   과학
20240001    100  90  100
2022100392   89  90   80
2022100390   70  80   92

In [40]:
df2 = df2.sort_index(ascending= True)

In [41]:
df2

             국어  수학   과학
20240001    100  90  100
2022100390   70  80   92
2022100392   89  90   80

In [42]:
pd.drop(df2['과학'])

AttributeError: module 'pandas' has no attribute 'drop'

In [43]:
df2.drop(['과학'], axis=1, inplace=True)
df2

             국어  수학
20240001    100  90
2022100390   70  80
2022100392   89  90

In [44]:
df2.drop([2022100390], axis=0, inplace=True)
df2

             국어  수학
20240001    100  90
2022100392   89  90

In [45]:
df2['과학'] = [100,100]
df2.insert(0, '역사', [100,90], allow_duplicates = False)
df2

             역사   국어  수학   과학
20240001    100  100  90  100
2022100392   90   89  90  100

In [46]:
df2.rename(columns = {'역사' : 'history'}, inplace=True)
df2.rename(index = {20240001 : '홍길동', 2022100392 : '최우식'}, inplace=True)
df2

     history   국어  수학   과학
홍길동      100  100  90  100
최우식       90   89  90  100

In [47]:
df2['history']

홍길동    100
최우식     90
Name: history, dtype: int64

In [48]:
df2[['국어','수학']]

      국어  수학
홍길동  100  90
최우식   89  90

In [49]:
df2[df2['국어'] >=89]

     history   국어  수학   과학
홍길동      100  100  90  100
최우식       90   89  90  100

In [50]:
df2[['수학','과학','history']]

     수학   과학  history
홍길동  90  100      100
최우식  90  100       90

In [51]:
df2[df2['history'] >=99]

     history   국어  수학   과학
홍길동      100  100  90  100

In [52]:
df2['총점'] = df2['국어']+df2['history'] + df2['수학']+df2['과학']
df2

     history   국어  수학   과학   총점
홍길동      100  100  90  100  390
최우식       90   89  90  100  369

In [53]:
df2['평균'] = df2['총점'] /4
df2.drop(['총점'], axis= 1, inplace=True)
df2

     history   국어  수학   과학     평균
홍길동      100  100  90  100  97.50
최우식       90   89  90  100  92.25

In [54]:
df2['평균'] = df2['평균'].round()

In [55]:
df2

     history   국어  수학   과학    평균
홍길동      100  100  90  100  98.0
최우식       90   89  90  100  92.0

In [56]:
df2[df2['평균'] >= 90]

     history   국어  수학   과학    평균
홍길동      100  100  90  100  98.0
최우식       90   89  90  100  92.0

In [57]:
import pandas as pd
df = pd.read_csv("./data/travel.csv", encoding="utf-8")
df.head()

,개방자치코드,인허가일자,영업상태코드,상세영업상태,소재지,도로명,사업장명,자본금
0,3000000,2008-03-10,4,등록취소,서울특별시 종로구 통의동 35-89번지 오리온빌딩 2층,"서울특별시 종로구 효자로 7-2 (통의동,오리온빌딩 2층)",(유)더에이치엔에스,38097000
1,3000000,1998-05-12,4,등록취소,서울특별시 종로구 내수동 4-0번지 옥빌딩601호,"서울특별시 종로구 새문안로5가길 11 (내수동,옥빌딩601호)",(주)보딩패스여행사,25243000
2,3000000,1998-08-10,4,등록취소,서울특별시 종로구 신문로1가 25-0번지 용마빌딩401호,NaN,(주)동성에어,4200000
3,3000000,1998-11-21,4,등록취소,서울특별시 종로구 청진동 244-0번지 한백빌딩3층,NaN,에스케이여행사,12044000
4,3000000,1999-03-12,4,등록취소,서울특별시 종로구 당주동 2-2번지,서울특별시 종로구 새문안로5가길 3-1 (당주동),(주)고산자답사회한국여행문화,34454000

In [58]:
type(df)

pandas.DataFrame

In [59]:
df.dtypes

개방자치코드    int64
인허가일자       str
영업상태코드    int64
상세영업상태      str
소재지         str
도로명         str
사업장명        str
자본금       int64
dtype: object

In [60]:
df.shape

(16349, 8)

In [61]:
print(df.index)
print()
print(df.columns)
print()
print(df.info())

RangeIndex(start=0, stop=16349, step=1)

Index(['개방자치코드', '인허가일자', '영업상태코드', '상세영업상태', '소재지', '도로명', '사업장명', '자본금'], dtype='str')

<class 'pandas.DataFrame'>
RangeIndex: 16349 entries, 0 to 16348
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   개방자치코드  16349 non-null  int64
 1   인허가일자   16349 non-null  str
 2   영업상태코드  16349 non-null  int64
 3   상세영업상태  16346 non-null  str
 4   소재지     16349 non-null  str
 5   도로명     15466 non-null  str
 6   사업장명    16349 non-null  str
 7   자본금     16349 non-null  int64
dtypes: int64(3), str(5)
memory usage: 1021.9 KB
None

In [62]:
df.describe()

             개방자치코드        영업상태코드           자본금
count  1.634900e+04  16349.000000  1.634900e+04
mean   4.218339e+06      2.643648  2.237446e+07
std    1.124560e+06      0.950638  1.295811e+07
min    3.000000e+06      1.000000  0.000000e+00
25%    3.250000e+06      3.000000  1.124100e+07
50%    3.780000e+06      3.000000  2.221400e+07
75%    5.000000e+06      3.000000  3.352400e+07
max    6.520000e+06      4.000000  7.450000e+07

In [63]:
df.values

array([[3000000, '2008-03-10', 4, ...,
        '서울특별시 종로구 효자로 7-2 (통의동,오리온빌딩 2층)', '(유)더에이치엔에스', 38097000],
       [3000000, '1998-05-12', 4, ...,
        '서울특별시 종로구 새문안로5가길 11  (내수동,옥빌딩601호)', '(주)보딩패스여행사', 25243000],
       [3000000, '1998-08-10', 4, ..., nan, '(주)동성에어', 4200000],
       ...,
       [6520000, '2012-12-21', 3, ..., '제주특별자치도 서귀포시 표선면 녹산로 381-15',
        '(주)이어도사나', 31727000],
       [6520000, '2013-04-22', 3, ..., '제주특별자치도 서귀포시 태평로 385 (서귀동)',
        'FUN TOUR', 33236000],
       [6520000, '2008-09-22', 3, ..., '제주특별자치도 서귀포시 남원읍 태위로 241-5',
        '큐츠', 8188000]], shape=(16349, 8), dtype=object)

In [64]:
df1 = pd.read_csv("./data/temperatures.csv", encoding="utf-8")
df2 = pd.concat([df, df1])
df2.head()

,개방자치코드,인허가일자,영업상태코드,상세영업상태,소재지,도로명,사업장명,자본금,날짜,기온
0,3000000.0,2008-03-10,4.0,등록취소,서울특별시 종로구 통의동 35-89번지 오리온빌딩 2층,"서울특별시 종로구 효자로 7-2 (통의동,오리온빌딩 2층)",(유)더에이치엔에스,38097000.0,NaN,NaN
1,3000000.0,1998-05-12,4.0,등록취소,서울특별시 종로구 내수동 4-0번지 옥빌딩601호,"서울특별시 종로구 새문안로5가길 11 (내수동,옥빌딩601호)",(주)보딩패스여행사,25243000.0,NaN,NaN
2,3000000.0,1998-08-10,4.0,등록취소,서울특별시 종로구 신문로1가 25-0번지 용마빌딩401호,NaN,(주)동성에어,4200000.0,NaN,NaN
3,3000000.0,1998-11-21,4.0,등록취소,서울특별시 종로구 청진동 244-0번지 한백빌딩3층,NaN,에스케이여행사,12044000.0,NaN,NaN
4,3000000.0,1999-03-12,4.0,등록취소,서울특별시 종로구 당주동 2-2번지,서울특별시 종로구 새문안로5가길 3-1 (당주동),(주)고산자답사회한국여행문화,34454000.0,NaN,NaN

In [65]:
df2.reset_index(drop=True, inplace=True)

In [66]:
df2.head()

,개방자치코드,인허가일자,영업상태코드,상세영업상태,소재지,도로명,사업장명,자본금,날짜,기온
0,3000000.0,2008-03-10,4.0,등록취소,서울특별시 종로구 통의동 35-89번지 오리온빌딩 2층,"서울특별시 종로구 효자로 7-2 (통의동,오리온빌딩 2층)",(유)더에이치엔에스,38097000.0,NaN,NaN
1,3000000.0,1998-05-12,4.0,등록취소,서울특별시 종로구 내수동 4-0번지 옥빌딩601호,"서울특별시 종로구 새문안로5가길 11 (내수동,옥빌딩601호)",(주)보딩패스여행사,25243000.0,NaN,NaN
2,3000000.0,1998-08-10,4.0,등록취소,서울특별시 종로구 신문로1가 25-0번지 용마빌딩401호,NaN,(주)동성에어,4200000.0,NaN,NaN
3,3000000.0,1998-11-21,4.0,등록취소,서울특별시 종로구 청진동 244-0번지 한백빌딩3층,NaN,에스케이여행사,12044000.0,NaN,NaN
4,3000000.0,1999-03-12,4.0,등록취소,서울특별시 종로구 당주동 2-2번지,서울특별시 종로구 새문안로5가길 3-1 (당주동),(주)고산자답사회한국여행문화,34454000.0,NaN,NaN

In [67]:
df.tail()

,개방자치코드,인허가일자,영업상태코드,상세영업상태,소재지,도로명,사업장명,자본금
16344,6520000,2017-02-02,3,폐업,제주특별자치도 서귀포시 성산읍 2040-1,제주특별자치도 서귀포시 성산읍 서성일로1168번길 89-17,찰쓰투어,12895000
16345,6520000,2012-11-21,3,폐업,제주특별자치도 서귀포시 서호동 1534번지 104동 1303호,"제주특별자치도 서귀포시 서호남로 91, 104동 1303호 (서호동, 서귀포혁신사랑...",(주)예나투어,43952000
16346,6520000,2012-12-21,3,폐업,제주특별자치도 서귀포시 표선면 가시리 3149-33번지,제주특별자치도 서귀포시 표선면 녹산로 381-15,(주)이어도사나,31727000
16347,6520000,2013-04-22,3,폐업,제주특별자치도 서귀포시 서귀동 455-4번지,제주특별자치도 서귀포시 태평로 385 (서귀동),FUN TOUR,33236000
16348,6520000,2008-09-22,3,폐업,제주특별자치도 서귀포시 남원읍 위미리 1600-3번지,제주특별자치도 서귀포시 남원읍 태위로 241-5,큐츠,8188000

In [68]:
import numpy as np
arr = df.head().to_numpy()
for i,k,l,m,n,o,p,f in arr :
    print(i,k,l,m,n,o,p,f, sep="\t")

3000000	2008-03-10	4	등록취소	서울특별시 종로구 통의동 35-89번지 오리온빌딩 2층 	서울특별시 종로구 효자로 7-2 (통의동,오리온빌딩 2층)	(유)더에이치엔에스	38097000
3000000	1998-05-12	4	등록취소	서울특별시 종로구 내수동 4-0번지 옥빌딩601호 	서울특별시 종로구 새문안로5가길 11  (내수동,옥빌딩601호)	(주)보딩패스여행사	25243000
3000000	1998-08-10	4	등록취소	서울특별시 종로구 신문로1가 25-0번지 용마빌딩401호 	nan	(주)동성에어	4200000
3000000	1998-11-21	4	등록취소	서울특별시 종로구 청진동 244-0번지 한백빌딩3층 	nan	에스케이여행사	12044000
3000000	1999-03-12	4	등록취소	서울특별시 종로구 당주동 2-2번지 	서울특별시 종로구 새문안로5가길 3-1  (당주동)	(주)고산자답사회한국여행문화	34454000

In [69]:
df = pd.read_csv("./data/job.csv", encoding="utf-8")
df.head()

  name from  age  job
0  나은미  경기    23   학생
1  정다혜   서울   35   교사
2  이은형   충남   29  공무원
3  김은미   강원   31  회사원
4  최성주   제주   35  매니저

In [70]:
df1 = pd.read_csv("./data/job1.csv", encoding="utf-8")
df1.head()

  name from  age  job
0   김민  전남    23   학생
1  정다은   경기   30  회사원
2  김인형   대전   38  공무원
3  최민수   충북   40   백수
4  최성미   제주   20  미용사

In [71]:
df = pd.concat([df,df1])
df

  name from  age  job
0  나은미  경기    23   학생
1  정다혜   서울   35   교사
2  이은형   충남   29  공무원
3  김은미   강원   31  회사원
4  최성주   제주   35  매니저
5  오달수   강원   55   배우
0   김민  전남    23   학생
1  정다은   경기   30  회사원
2  김인형   대전   38  공무원
3  최민수   충북   40   백수
4  최성미   제주   20  미용사
5  오미지   강원   13   학생

In [72]:
df.reset_index(drop=True, inplace=True)
df

   name from  age  job
0   나은미  경기    23   학생
1   정다혜   서울   35   교사
2   이은형   충남   29  공무원
3   김은미   강원   31  회사원
4   최성주   제주   35  매니저
5   오달수   강원   55   배우
6    김민  전남    23   학생
7   정다은   경기   30  회사원
8   김인형   대전   38  공무원
9   최민수   충북   40   백수
10  최성미   제주   20  미용사
11  오미지   강원   13   학생

In [73]:
import pandas as pd
group = df.groupby('from', as_index=False).sum()
group

  from       name  age      job
0   강원  김은미오달수오미지   99  회사원배우학생
1   경기        정다은   30      회사원
2  경기         나은미   23       학생
3   대전        김인형   38      공무원
4   서울        정다혜   35       교사
5  전남          김민   23       학생
6   제주     최성주최성미   55   매니저미용사
7   충남        이은형   29      공무원
8   충북        최민수   40       백수

In [74]:
df = pd.read_csv("./data/product.csv", encoding="utf-8")
df1 = pd.read_csv("./data/product1.csv", encoding="utf-8")
print(df)
print()
print(df1)

         판매일자      제품명  판매수량     판매단가      판매금액
0  2023.05.15      액세스    15   225000   3375000
1  2023.05.15   컴퓨터 활용    32   416000  13312000
2  2023.05.15     전산개론    15   217500   3262500
3  2023.05.15  멀티미디어개론    80  1120000  89600000
4  2023.05.15   C언어 입문    12   216000   2592000
5  2023.05.15     자바입문    25   400000  10000000

         판매일자           제품명  판매수량     판매단가       판매금액
0  2023.05.16  Visual Basic    10   225000    2250000
1  2023.05.16        컴퓨터 활용    20   416000    8320000
2  2023.05.16          전산개론    80   217500   17400000
3  2023.05.16          자료구조   100  1120000  112000000
4  2023.05.17          자료구조     2   216000     432000
5  2023.05.17          자바입문    88   400000   35200000

In [75]:
df = pd.concat([df,df1])
df.reset_index(drop=True, inplace=True)
df

          판매일자           제품명  판매수량     판매단가       판매금액
0   2023.05.15           액세스    15   225000    3375000
1   2023.05.15        컴퓨터 활용    32   416000   13312000
2   2023.05.15          전산개론    15   217500    3262500
3   2023.05.15       멀티미디어개론    80  1120000   89600000
4   2023.05.15        C언어 입문    12   216000    2592000
5   2023.05.15          자바입문    25   400000   10000000
6   2023.05.16  Visual Basic    10   225000    2250000
7   2023.05.16        컴퓨터 활용    20   416000    8320000
8   2023.05.16          전산개론    80   217500   17400000
9   2023.05.16          자료구조   100  1120000  112000000
10  2023.05.17          자료구조     2   216000     432000
11  2023.05.17          자바입문    88   400000   35200000

In [76]:
group = df.groupby(['판매일자'], as_index=False).sum()[['판매일자','판매수량','판매단가','판매금액']]

In [77]:
group

         판매일자  판매수량     판매단가       판매금액
0  2023.05.15   179  2594500  122141500
1  2023.05.16   210  1978500  139970000
2  2023.05.17    90   616000   35632000

In [78]:
df.to_csv("C:\\example_folder

SyntaxError: unterminated string literal (detected at line 1) (2813643804.py, line 1)