In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("./data/sungjuk.csv", encoding="utf-8")
df.isnull().sum()

name     3
kor      8
eng      6
math    18
dtype: int64

In [2]:
df.dropna(subset=['name'], inplace=True)

In [3]:
df

   name    kor   eng  math
0   윤수진   90.0  80.0   NaN
1   김은숙   90.0   NaN   NaN
2   강수길   80.0  70.0   NaN
3   문영숙    NaN  90.0   NaN
4   김경은  100.0  80.0   NaN
5   정유진   70.0   NaN   NaN
6   윤경희   90.0  85.0   NaN
7   이은비   60.0  90.0   NaN
8   장은아    NaN   NaN   NaN
9   남희진    NaN  60.0   NaN
10  김수빈   70.0   0.0   NaN
11  박은진   85.0  85.0   NaN
12  김성경  100.0  85.0   NaN
13  이수정    NaN  90.0   NaN
14  박현아    NaN  80.0   NaN

In [4]:
df = df[df.isnull().sum(axis=1) <2]
df

   name    kor   eng  math
0   윤수진   90.0  80.0   NaN
2   강수길   80.0  70.0   NaN
4   김경은  100.0  80.0   NaN
6   윤경희   90.0  85.0   NaN
7   이은비   60.0  90.0   NaN
10  김수빈   70.0   0.0   NaN
11  박은진   85.0  85.0   NaN
12  김성경  100.0  85.0   NaN

In [5]:
df.fillna(0, inplace=True)

   name    kor   eng  math
0   윤수진   90.0  80.0   0.0
2   강수길   80.0  70.0   0.0
4   김경은  100.0  80.0   0.0
6   윤경희   90.0  85.0   0.0
7   이은비   60.0  90.0   0.0
10  김수빈   70.0   0.0   0.0
11  박은진   85.0  85.0   0.0
12  김성경  100.0  85.0   0.0

In [6]:
df

   name    kor   eng  math
0   윤수진   90.0  80.0   0.0
2   강수길   80.0  70.0   0.0
4   김경은  100.0  80.0   0.0
6   윤경희   90.0  85.0   0.0
7   이은비   60.0  90.0   0.0
10  김수빈   70.0   0.0   0.0
11  박은진   85.0  85.0   0.0
12  김성경  100.0  85.0   0.0

In [7]:
df[['kor','eng','math']] = df[['kor','eng','math']].astype(int)

In [8]:
df

   name  kor  eng  math
0   윤수진   90   80     0
2   강수길   80   70     0
4   김경은  100   80     0
6   윤경희   90   85     0
7   이은비   60   90     0
10  김수빈   70    0     0
11  박은진   85   85     0
12  김성경  100   85     0

In [9]:
df.reset_index(drop=True, inplace=True)

In [10]:
df

  name  kor  eng  math
0  윤수진   90   80     0
1  강수길   80   70     0
2  김경은  100   80     0
3  윤경희   90   85     0
4  이은비   60   90     0
5  김수빈   70    0     0
6  박은진   85   85     0
7  김성경  100   85     0

In [11]:
df.loc[8] = ['이은비',60,90,0]
df[df.duplicated(keep=False)]

  name  kor  eng  math
4  이은비   60   90     0
8  이은비   60   90     0

In [12]:
df.drop_duplicates(keep="first", inplace=True)

In [13]:
df

  name  kor  eng  math
0  윤수진   90   80     0
1  강수길   80   70     0
2  김경은  100   80     0
3  윤경희   90   85     0
4  이은비   60   90     0
5  김수빈   70    0     0
6  박은진   85   85     0
7  김성경  100   85     0

In [14]:
df.drop('math', axis=1, inplace=True)

In [15]:
df

  name  kor  eng
0  윤수진   90   80
1  강수길   80   70
2  김경은  100   80
3  윤경희   90   85
4  이은비   60   90
5  김수빈   70    0
6  박은진   85   85
7  김성경  100   85

In [16]:
df = df[(df['kor'] != 0) & (df['eng'] != 0)]
df

  name  kor  eng
0  윤수진   90   80
1  강수길   80   70
2  김경은  100   80
3  윤경희   90   85
4  이은비   60   90
6  박은진   85   85
7  김성경  100   85

In [17]:
df.loc[df['kor'] <= 60, 'kor'] = 65

In [18]:
df['순위'] = (df['kor']+df['eng']).rank(method="dense", ascending= False)
df['순위'] = df['순위'].astype(int)

In [19]:
df

  name  kor  eng  순위
0  윤수진   90   80   4
1  강수길   80   70   6
2  김경은  100   80   2
3  윤경희   90   85   3
4  이은비   65   90   5
6  박은진   85   85   4
7  김성경  100   85   1

In [20]:
df =df.sort_values('순위', ascending = True)

In [21]:
df

  name  kor  eng  순위
7  김성경  100   85   1
2  김경은  100   80   2
3  윤경희   90   85   3
0  윤수진   90   80   4
6  박은진   85   85   4
4  이은비   65   90   5
1  강수길   80   70   6