In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("./data/분양가동향.csv", encoding="cp949")
df.head()

,분류,2024년 7월,2024년 8월,2024년 9월,2024년 10월,2024년 11월,2024년 12월,2025년 1월,2025년 2월,2025년 3월,2025년 4월
0,전국,"""455,505""","""459,422""","""462,147""","""463,554""","""464,280""","""464,370""","""464,107""","""464,641""","""467,110""","""473,012"""
1,수도권,"""676,207""","""684,514""","""690,207""","""693,269""","""695,031""","""695,663""","""695,608""","""697,106""","""702,761""","""708,755"""
2,지방권,"""255,451""","""255,389""","""255,425""","""255,330""","""255,119""","""254,717""","""254,265""","""253,925""","""253,507""","""259,175"""
3,6대광역시,"""335,574""","""335,982""","""336,286""","""336,196""","""335,866""","""335,113""","""334,367""","""333,749""","""333,022""","""340,337"""
4,5대광역시,"""325,247""","""324,986""","""324,931""","""324,587""","""324,148""","""323,497""","""322,835""","""322,253""","""321,590""","""328,643"""

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 239 entries, 0 to 238
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   분류         239 non-null    str
 1   2024년 7월   230 non-null    str
 2   2024년 8월   230 non-null    str
 3   2024년 9월   230 non-null    str
 4   2024년 10월  230 non-null    str
 5   2024년 11월  230 non-null    str
 6   2024년 12월  230 non-null    str
 7   2025년 1월   230 non-null    str
 8   2025년 2월   230 non-null    str
 9   2025년 3월   230 non-null    str
 10  2025년 4월   230 non-null    str
dtypes: str(11)
memory usage: 20.7 KB

In [3]:
df["2024/07"] = pd.to_numeric(df['2024년 7월'], errors="coerce")
df.head()

,분류,2024년 7월,2024년 8월,2024년 9월,2024년 10월,2024년 11월,2024년 12월,2025년 1월,2025년 2월,2025년 3월,2025년 4월,2024/07
0,전국,"""455,505""","""459,422""","""462,147""","""463,554""","""464,280""","""464,370""","""464,107""","""464,641""","""467,110""","""473,012""",NaN
1,수도권,"""676,207""","""684,514""","""690,207""","""693,269""","""695,031""","""695,663""","""695,608""","""697,106""","""702,761""","""708,755""",NaN
2,지방권,"""255,451""","""255,389""","""255,425""","""255,330""","""255,119""","""254,717""","""254,265""","""253,925""","""253,507""","""259,175""",NaN
3,6대광역시,"""335,574""","""335,982""","""336,286""","""336,196""","""335,866""","""335,113""","""334,367""","""333,749""","""333,022""","""340,337""",NaN
4,5대광역시,"""325,247""","""324,986""","""324,931""","""324,587""","""324,148""","""323,497""","""322,835""","""322,253""","""321,590""","""328,643""",NaN

In [4]:
df.drop('분류', axis=1, inplace=True)
df.head()

,2024년 7월,2024년 8월,2024년 9월,2024년 10월,2024년 11월,2024년 12월,2025년 1월,2025년 2월,2025년 3월,2025년 4월,2024/07
0,"""455,505""","""459,422""","""462,147""","""463,554""","""464,280""","""464,370""","""464,107""","""464,641""","""467,110""","""473,012""",NaN
1,"""676,207""","""684,514""","""690,207""","""693,269""","""695,031""","""695,663""","""695,608""","""697,106""","""702,761""","""708,755""",NaN
2,"""255,451""","""255,389""","""255,425""","""255,330""","""255,119""","""254,717""","""254,265""","""253,925""","""253,507""","""259,175""",NaN
3,"""335,574""","""335,982""","""336,286""","""336,196""","""335,866""","""335,113""","""334,367""","""333,749""","""333,022""","""340,337""",NaN
4,"""325,247""","""324,986""","""324,931""","""324,587""","""324,148""","""323,497""","""322,835""","""322,253""","""321,590""","""328,643""",NaN

In [5]:
df.drop(['2024/07'], axis=1, inplace=True)

In [6]:
df.head()

,2024년 7월,2024년 8월,2024년 9월,2024년 10월,2024년 11월,2024년 12월,2025년 1월,2025년 2월,2025년 3월,2025년 4월
0,"""455,505""","""459,422""","""462,147""","""463,554""","""464,280""","""464,370""","""464,107""","""464,641""","""467,110""","""473,012"""
1,"""676,207""","""684,514""","""690,207""","""693,269""","""695,031""","""695,663""","""695,608""","""697,106""","""702,761""","""708,755"""
2,"""255,451""","""255,389""","""255,425""","""255,330""","""255,119""","""254,717""","""254,265""","""253,925""","""253,507""","""259,175"""
3,"""335,574""","""335,982""","""336,286""","""336,196""","""335,866""","""335,113""","""334,367""","""333,749""","""333,022""","""340,337"""
4,"""325,247""","""324,986""","""324,931""","""324,587""","""324,148""","""323,497""","""322,835""","""322,253""","""321,590""","""328,643"""

In [7]:
df = pd.read_csv("./data/분양가동향.csv", encoding="cp949")
df.query('분류 == "서울"')

,분류,2024년 7월,2024년 8월,2024년 9월,2024년 10월,2024년 11월,2024년 12월,2025년 1월,2025년 2월,2025년 3월,2025년 4월
7,서울,"""1,082,648""","""1,101,592""","""1,113,526""","""1,120,374""","""1,124,638""","""1,126,489""","""1,127,466""","""1,133,449""","""1,151,101""","""1,166,337"""

In [8]:
df.query('분류== "남구"')

,분류,2024년 7월,2024년 8월,2024년 9월,2024년 10월,2024년 11월,2024년 12월,2025년 1월,2025년 2월,2025년 3월,2025년 4월
102,남구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,남구,"""434,164""","""433,149""","""432,499""","""430,918""","""430,851""","""429,785""","""429,926""","""430,188""","""429,850""","""430,525"""
133,남구,"""300,191""","""298,241""","""295,776""","""294,277""","""293,143""","""291,663""","""290,413""","""289,395""","""287,952""","""294,870"""
141,남구,"""323,168""","""323,336""","""323,471""","""322,900""","""322,724""","""322,271""","""321,722""","""320,686""","""319,561""","""323,387"""
152,남구,"""381,026""","""381,104""","""381,117""","""381,748""","""382,582""","""382,563""","""382,456""","""382,729""","""382,895""","""392,797"""
210,남구,"""194,574""","""194,489""","""195,456""","""194,971""","""195,034""","""194,458""","""194,102""","""193,586""","""193,173""","""194,095"""

In [9]:
df[df['분류']=='남구']

,분류,2024년 7월,2024년 8월,2024년 9월,2024년 10월,2024년 11월,2024년 12월,2025년 1월,2025년 2월,2025년 3월,2025년 4월
102,남구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,남구,"""434,164""","""433,149""","""432,499""","""430,918""","""430,851""","""429,785""","""429,926""","""430,188""","""429,850""","""430,525"""
133,남구,"""300,191""","""298,241""","""295,776""","""294,277""","""293,143""","""291,663""","""290,413""","""289,395""","""287,952""","""294,870"""
141,남구,"""323,168""","""323,336""","""323,471""","""322,900""","""322,724""","""322,271""","""321,722""","""320,686""","""319,561""","""323,387"""
152,남구,"""381,026""","""381,104""","""381,117""","""381,748""","""382,582""","""382,563""","""382,456""","""382,729""","""382,895""","""392,797"""
210,남구,"""194,574""","""194,489""","""195,456""","""194,971""","""195,034""","""194,458""","""194,102""","""193,586""","""193,173""","""194,095"""

In [10]:
df.query("분류.str.contains('동구')").head()

,분류,2024년 7월,2024년 8월,2024년 9월,2024년 10월,2024년 11월,2024년 12월,2025년 1월,2025년 2월,2025년 3월,2025년 4월
14,성동구,"""1,381,157""","""1,418,900""","""1,436,781""","""1,448,295""","""1,456,752""","""1,458,733""","""1,460,167""","""1,462,662""","""1,479,133""","""1,491,938"""
39,강동구,"""954,490""","""970,087""","""977,838""","""982,455""","""983,814""","""982,731""","""982,526""","""985,372""","""997,087""","""1,001,485"""
91,일산동구,"""599,576""","""600,674""","""603,879""","""606,208""","""606,543""","""605,199""","""603,998""","""603,475""","""601,895""","""597,908"""
101,동구,"""182,969""","""184,377""","""185,669""","""186,132""","""186,364""","""186,272""","""185,847""","""185,716""","""185,378""","""188,138"""
105,남동구,"""349,729""","""352,497""","""353,643""","""353,774""","""353,238""","""351,593""","""349,934""","""348,928""","""348,565""","""350,892"""

In [11]:
df.query("분류=='남구' or 분류=='북구'").head()

,분류,2024년 7월,2024년 8월,2024년 9월,2024년 10월,2024년 11월,2024년 12월,2025년 1월,2025년 2월,2025년 3월,2025년 4월
102,남구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,남구,"""434,164""","""433,149""","""432,499""","""430,918""","""430,851""","""429,785""","""429,926""","""430,188""","""429,850""","""430,525"""
125,북구,"""292,634""","""292,892""","""292,611""","""292,765""","""292,367""","""291,836""","""290,962""","""291,107""","""290,884""","""297,488"""
133,남구,"""300,191""","""298,241""","""295,776""","""294,277""","""293,143""","""291,663""","""290,413""","""289,395""","""287,952""","""294,870"""
134,북구,"""246,629""","""245,940""","""245,329""","""244,582""","""243,771""","""243,147""","""241,948""","""240,327""","""238,747""","""241,523"""

In [12]:
df[(df['분류']=='남구') | (df['분류'] == '북구')]

,분류,2024년 7월,2024년 8월,2024년 9월,2024년 10월,2024년 11월,2024년 12월,2025년 1월,2025년 2월,2025년 3월,2025년 4월
102,남구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,남구,"""434,164""","""433,149""","""432,499""","""430,918""","""430,851""","""429,785""","""429,926""","""430,188""","""429,850""","""430,525"""
125,북구,"""292,634""","""292,892""","""292,611""","""292,765""","""292,367""","""291,836""","""290,962""","""291,107""","""290,884""","""297,488"""
133,남구,"""300,191""","""298,241""","""295,776""","""294,277""","""293,143""","""291,663""","""290,413""","""289,395""","""287,952""","""294,870"""
134,북구,"""246,629""","""245,940""","""245,329""","""244,582""","""243,771""","""243,147""","""241,948""","""240,327""","""238,747""","""241,523"""
141,남구,"""323,168""","""323,336""","""323,471""","""322,900""","""322,724""","""322,271""","""321,722""","""320,686""","""319,561""","""323,387"""
142,북구,"""220,788""","""220,552""","""220,309""","""219,764""","""219,505""","""219,196""","""218,897""","""218,488""","""218,144""","""225,031"""
152,남구,"""381,026""","""381,104""","""381,117""","""381,748""","""382,582""","""382,563""","""382,456""","""382,729""","""382,895""","""392,797"""
154,북구,"""254,567""","""254,815""","""255,226""","""255,471""","""255,677""","""255,824""","""256,010""","""256,172""","""256,967""","""265,724"""
210,남구,"""194,574""","""194,489""","""195,456""","""194,971""","""195,034""","""194,458""","""194,102""","""193,586""","""193,173""","""194,095"""
211,북구,"""171,236""","""171,100""","""170,776""","""170,693""","""170,522""","""169,686""","""169,257""","""168,562""","""167,769""","""174,714"""

In [13]:
df['분류'].unique()

<StringArray>
[   '전국',   '수도권',   '지방권', '6대광역시', '5대광역시',   '9개도',   '8개도',    '서울',
  '강북지역',   '도심권',
 ...
   '진주시',   '통영시',   '사천시',   '김해시',   '밀양시',   '거제시',   '양산시',    '제주',
   '제주시',  '서귀포시']
Length: 215, dtype: str

In [14]:
df['분류'].nunique()

215

In [15]:
! pip install missingno

Requirement already satisfied: missingno in /usr/local/lib/python3.11/dist-packages (0.5.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from missingno) (2.4.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from missingno) (3.10.9)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from missingno) (1.17.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (from missingno) (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (26.1)

Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/lib/python3.11/dist-packages (from matplotlib->missingno) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /root/.local/lib/python3.11/site-packages (from matplotlib->missingno) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.11/dist-packages (from seaborn->missingno) (3.0.2)

Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->missingno) (1.17.0)

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [16]:

plt.figure((10,8))
plt.rcParams['font.family'] = 'malgun gothic'
sns.heatmap(df.isnull(), cbar=False)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'tuple'

In [17]:
df.isna().sum()

분류           0
2024년 7월     9
2024년 8월     9
2024년 9월     9
2024년 10월    9
2024년 11월    9
2024년 12월    9
2025년 1월     9
2025년 2월     9
2025년 3월     9
2025년 4월     9
dtype: int64

In [18]:
df.isnull().sum()

분류           0
2024년 7월     9
2024년 8월     9
2024년 9월     9
2024년 10월    9
2024년 11월    9
2024년 12월    9
2025년 1월     9
2025년 2월     9
2025년 3월     9
2025년 4월     9
dtype: int64

In [19]:
df.dropna(how='any', axis=0, inplace=True)
df.isnull().sum()

분류           0
2024년 7월     0
2024년 8월     0
2024년 9월     0
2024년 10월    0
2024년 11월    0
2024년 12월    0
2025년 1월     0
2025년 2월     0
2025년 3월     0
2025년 4월     0
dtype: int64

In [20]:
new = df.groupby(['지역명'])['평당분양가'].mean()
new.sort_values(ascending=True)
a = df.groupby(['연도','지역명'])['평당분양가'].mean()
d = df.groupby(['연도','지역명'])['평당분양가'].mean().stack().round()

KeyError: '지역명'

In [21]:
df = pd.read_csv("./data/분양가동향.csv", encoding="cp949")
df.dropna(how='any', axis=0, inplace=True)
df.isna().sum()

분류           0
2024년 7월     0
2024년 8월     0
2024년 9월     0
2024년 10월    0
2024년 11월    0
2024년 12월    0
2025년 1월     0
2025년 2월     0
2025년 3월     0
2025년 4월     0
dtype: int64

In [22]:
a = df.pivot_table(df1, index=['연도','지역명'],values='평당분양가', aggfunc=['max','mean',' min']).round()

NameError: name 'df1' is not defined